### ISSUE TITLE
Add auto-completion for city names

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#10]
Add auto completion for city names in new patient report forms so that the users don't make spelling errors or alternate spellings when entering the information

**Comment by kiranbkrishna** [comment]
Do you have a list of all cities?

**Comment by vijaysaimutyala** [comment]
Found an api (here)[https://indian-cities-api-nocbegfhqg.now.sh/cities]. It has around 5161 cities. Also I dont see the report patient link in the home page on https://covid19-india.now.sh/
