### ISSUE TITLE
Add a error report review queue

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#18]
The user details page provides a way for users to leave error reports in the app. The moderators should be able to see these error reports associated with each patient so that they can make necessary corrections.

**Comment by Ajuajmal** [comment]
Hey I  added Error Report Queue option, just checkout the demo link
#### Preview
https://ed4c830f.ngrok.io/error-report-queue
**temp creds'**
username : `admin`
password: `12345`
https://ed4c830f.ngrok.io/admin

### ScreenShots

**Comment by tecoholic** [comment]
Can we get rid of the intermediate page and directly go to the patient form page? Probably do something like this.

![error_report_review](https://user-images.githubusercontent.com/383862/77379050-b14b0c00-6d9d-11ea-99d5-cd048f2e0b85.png)

This essentially will have two forms. Once an update form for the patient, the other which will discard the error report. For the sake of two columns maybe we can change the patient update form from being a horizontal form to a normal one?

What do you think? I think this will make the UX better.

**Comment by tecoholic** [comment]
The error can be seen from patient detail page or the dedicated error queue page.
![two_ways](https://user-images.githubusercontent.com/383862/77418861-84264a00-6ded-11ea-97f6-579b58664117.png)

Error queue page
![Error_reports](https://user-images.githubusercontent.com/383862/77418905-91433900-6ded-11ea-9667-f134f7fef014.png)

And then all the reports of the paitent are displayed along with a form to correct details if necessary
![error_review_page](https://user-images.githubusercontent.com/383862/77418964-a8822680-6ded-11ea-9762-8191d9ef389b.png)
