### ISSUE TITLE
District Selection not working in the report page

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#21]
The Report Model in `patients/models.py` defines an empty list for the choices list, so the form validation fails. This should be fixed either using a custom validator for the `detected_district` field in the model or all the districts in the `patients/constants.py` file should be added to the choices to make sure validation works.

I would prefer to see a custom validator which not only checks the district, but also that the district is actually from that state.

**Comment by tecoholic** [comment]
![report-page](https://user-images.githubusercontent.com/383862/77250541-b8273100-6c6e-11ea-89bf-9d5440187bfc.png)

**Comment by vijaysaimutyala** [comment]
Fixed the issue. Will submit a PR shortly. Thanks.

**Comment by vijaysaimutyala** [comment]
PR https://github.com/covid19india/CovidCrowd/pull/27 submitted and accepted. Hence closing the issue.
