### ISSUE TITLE
Create a new model & view for Travel History of patients

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#22]
With the Kerala govt releasing the travel history of the patients, a new requirement has come up for the portal. CovidCrowd should have a model that can collect this data and store in a structured fashion tying it to the patient.

![travel-history](https://user-images.githubusercontent.com/383862/77250726-cde92600-6c6f-11ea-84f1-ff8106c2893e.png)

A new create/update view needs to be created for the data to be added to the application.

**Comment by tecoholic** [comment]
Look at `data/travel_history.csv` for file.

**Comment by tamizhgeek** [comment]
Here is a PR: https://github.com/covid19india/CovidCrowd/pull/37 Let me know what you think?

**Comment by tecoholic** [comment]
It was much needed. Thanks for adding the import support even though I haven't mentioned it in the ticket. It was thoughtful of you. I will update the README. 

Closed with PR #37
