### ISSUE TITLE
Update the importcsv action to reflect the change in data structure

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#24]
The data structure in the google sheet has changed since the data was last imported. Refer to the google sheets for the latest `raw_data` structure and update the importcsv functionality to refer to the right columns.

**Comment by harish2704** [comment]
I think you have fixed this issue in https://github.com/covid19india/CovidCrowd/commit/d1e24bcca838440b4d56f65227eb9202953ba140

Isn't it?

**Comment by tecoholic** [comment]
Yeah. this should be closed.
