### ISSUE TITLE
Add a state view

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#26]
The aim of this view is to show all the information about a particular state.

* metrics like confirmed, deaths, recoveries
* list of patients in the database
* no.of cities/districts involved
* a heatmap of the state with the reported cases ...etc.,

**Comment by userhasnoname0** [comment]
Hi,

As currently confirmed metric of district of a particular state view is being shown, can we go ahead with death count too ? and delta value in death state-wise is not being shown.
