### ISSUE TITLE
Improve the City Autocomplete UI

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#28]
The autocomplete UI in the `report.html` is producing a list of items which are unstyled and looks out of place.

![autocomplete](https://user-images.githubusercontent.com/383862/77251685-c3318f80-6c75-11ea-809b-b63b58347803.png)

Add some styling to it look more intutive.

**Comment by Ajuajmal** [comment]
I did some modifications , just check at http://03f55971.ngrok.io/report
![Screenshot from 2020-03-22 22-08-39](https://user-images.githubusercontent.com/28041916/77254910-e2d2b300-6c89-11ea-9f02-1eea95f4593b.png)

**Comment by tecoholic** [comment]
I am sorry, I didn't see this at that time. I was working on a fix myself :)
![dropdown](https://user-images.githubusercontent.com/383862/77255977-51673f00-6c91-11ea-9f43-9e0d972a7c67.png)
