### ISSUE TITLE
Create an api for the patient object

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#32]
The application already has Django Rest Framework included. Setup a `/api/patients` GET endpoint that returns the patient objects.

**Comment by Ajuajmal** [comment]
Hey, I just wrote an api for getting all patient objects just have a look at http://03f55971.ngrok.io/api/v1/patients/

**Comment by Ajuajmal** [comment]
do we need to add on option for getting a single patient object by some id or this one is fine !?

**Comment by tecoholic** [comment]
@Ajuajmal Thank you for this. We can have a separate endpoint for a single patient as well. I think it might be useful for some. Can we restrict the API to GET alone? At this point we don't want to handle authentication at the API level and support POST

**Comment by Ajuajmal** [comment]
Okay, I made the API to GET alone
