### ISSUE TITLE
Add Government ID field to the Report page

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#39]
State goverments have their of IDs for patients to keep track of the data. The report form should have a optional field that will accept this value.

Reference of state ID
![P52](https://user-images.githubusercontent.com/383862/77278684-ff043d80-6ce5-11ea-9ce1-000376af7088.jpg)

**Comment by dparikh85** [comment]
Hi Arun, 
      I would like to contribute to this. How can we proceed with this?

**Comment by tecoholic** [comment]
@dparikh85 Hi, This project is no longer maintained. Sorry about that.
