### ISSUE TITLE
Migrate existing dataset into the application

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#4]
The current dataset needs to be migrated to this application once deployed.

**Comment by baijum** [comment]
Can anyone please confirm whether this is the current dataset?
https://api.rootnet.in/covid19-in/unofficial/covid19india.org

**Comment by tecoholic** [comment]
> Can anyone please confirm whether this is the current dataset?
> https://api.rootnet.in/covid19-in/unofficial/covid19india.org

Short Answer: Yes

Full answer: The current data lives in a Google Spreadsheet, and the API endpoint above is gets that data and serves it as an API

**Comment by tecoholic** [comment]
This is done with the `importcsv` CSV command now.
