### ISSUE TITLE
Migrate the frontend to a JS client SPA

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#54]
The loads to the portal are higher than estimated and as in every dynamic application, the template compilation exerts a big load on the system. So planning to move to a React/Vue frontend to let the browser handle all the UI template compilation and make the Django App a API server (at least for the public pages)

**Comment by tecoholic** [comment]
There are only 3 pages that need to be done:

### 1. The home page which needs a table with sorting, searching and filtering options.

![image](https://user-images.githubusercontent.com/383862/77527592-6b339c80-6eb2-11ea-93c7-666f02d661ed.png)

### 2. A patient detail page which shows the details in a neat way

![image](https://user-images.githubusercontent.com/383862/77527652-89010180-6eb2-11ea-9244-81e5bd2963b5.png)

### 3. A report form that will collect new reports

![image](https://user-images.githubusercontent.com/383862/77527683-9f0ec200-6eb2-11ea-8dbe-aafddae88902.png)

**Comment by tecoholic** [comment]
The form should have better fields like this https://docs.google.com/forms/d/e/1FAIpQLSceGZmMCKjAcVkjL0xrGH3XwZUiOGisS_SVr7qYdSP2y2YHbA/viewform

**Comment by RohithCIS** [comment]
I can Help. I will get started.
