### ISSUE TITLE
Check deploy instructions

### ISSUE THREAD

**Issue by kdnanmaga** [covid19india/CovidCrowd#56]
Trying to deploy on a spare server. 

I guess it needs python3-venv instead of python3-virtualenv. Can you please check and change the initial dependency installation instruction accordingly?

**Comment by 83bytes** [comment]
Do you mean the line that says 
`ptyhon3 -m venv env` ? 

What is the error that you are getting ?

**Comment by kdnanmaga** [comment]
Found some typos in the deploy instructions.

Will make edits and send a PR. Compare and see what needs to be fixed.

**Comment by ThePiyushGupta** [comment]
I am getting this error
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by 83bytes** [comment]
https://github.com/covid19india/CovidCrowd/tree/master/deployment#setup-the-django-app

You will need to set the SECRET_KEY, DEBUG_FLAG and MY_HOST values for the app to function. 

You can put anything this variable...

SECRET_KEY=testing

**Comment by kdnanmaga** [comment]
I got that working...
In sudo apt install, you had mentioned python3-virtualenv instead of python3-venv. Have sent a PR anyway. There were some other minor typos as well. 

Have sent a PR, please have a look.
