### ISSUE TITLE
Change the typo for district entries

### ISSUE THREAD

**Issue by sheshang** [covid19india/CovidCrowd#60]
in raw data, Kerala district "Kasaragod" is also been listed as "Kasargod" in 4 entries. That has made the two clusters district wise. "Kasargod" needs to be changed to the "Kasaragod" to have a single cluster with total cases.
This also maps to the  https://github.com/covid19india/api/issues/9

**Comment by 22shubh22** [comment]
@sheshang I am interested, where can I do it.
