### ISSUE TITLE
Move Telegram link out of the home page. 

### ISSUE THREAD

**Issue by aswaathb** [covid19india/CovidCrowd#61]
Remove the telegram invite button from the home page to curb spam on the ops chat. People who are genuinely interested can use the same button on the FAQ. That way they'd have read the FAQs at least.

**Comment by ShwetaTurakhia** [comment]
I would like to work on this change. Just to confirm, you want this link "JOIN TELEGRAM TO COLLABORATE!' to be removed, right?

**Comment by tecoholic** [comment]
This should be in the https://github.com/covid19india/covid19india-react repository
